### ISSUE TITLE
Run but just using static_examples

### ISSUE THREAD

**Issue by emanuelef** [isaacloud/local-api#11]
Hi,
great tool, I'm trying to understand how to use it for my needs.
I guess many have already some generated JSON in example folder.
Is there an option to use just those instead of generating from templates (I read about static_examples but even if I copied my json samples there I get an error: error:  context=while reading examples/devices.json, context_mark=null, message=cannot read examples/devices.json (Error: ENOENT: no such file or directory, open 'examples/devices.json'), name=vSTB.raml, line=25, column=24, buffer=#%RAML 0.8
---).
Thanks

**Comment by mszopa** [comment]
Hi emanuelef,
to use static examples, you will need to change the `example` paths in your *.raml to include files from static_example folder. For instance:
```
example: !include static-examples/devices.json
```
Cheers!

**Comment by emanuelef** [comment]
Hi, 
thanks for replying, I tried that but didn't work.
I have a static_examples folder and in the RAML I refer to it like this:

!include ../static_examples/genericdevices.json (if inside a separate RAML for resource types)
or
!include static_examples/devices.json (if inside the main RAML)

In your post you used static-examples, was the - a typo ?

**Comment by emanuelef** [comment]
Thanks that worked,
(in my include I used _ probably the - in your example was just a typo).
I wanted to keep examples as folder to avoid changing folder name for other tools. Also it would be useful to switch to generated examples to static ones without changing the RAML.
