### ISSUE TITLE
Installation error: sudo npm install -g localapi

### ISSUE THREAD

**Issue by patoi** [isaacloud/local-api#18]
sudo npm install -g localapi
 
> fmerge@1.2.0 install /root/.nvm/versions/node/v4.2.3/lib/node_modules/localapi/node_modules/find-remove/node_modules/fmerge
> node install.js

/
module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/versions/node/v4.2.3/lib/node_modules/localapi/node_modules/find-remove/node_modules/fmerge/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/root/.nvm/versions/node/v4.2.3/bin/node" "/root/.nvm/versions/node/v4.2.3/bin/npm" "install" "-g" "localapi"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! fmerge@1.2.0 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the fmerge@1.2.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the fmerge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fmerge
npm ERR! There is likely additional logging output above.

**Comment by asikorski** [comment]
@patoi  Today we release new version (1.4.2) with some bugfix, please try now.

**Comment by patoi** [comment]
Thanks, it's ok!
