### ISSUE TITLE
Request content type is checked against response content type

### ISSUE THREAD

**Issue by greenrd** [isaacloud/local-api#3]
If the RAML file defines a request's content type to be `application/x-www-form-urlencoded`, and the response's content type to be (by default) `application/json`, when a request with content type `application/x-www-form-urlencoded` is sent, local-api will error with `Error: Content-Type application/x-www-form-urlencoded is not specified for this resource`.

It seems that local-api incorrectly assumes that the content-type for responses specify what should be returned in response to different content-types in requests. This is not the case; they do not define such logic, but merely distinguish between different content-types which may be returned by different responses from the same resource. The RAML spec is confusingly written in this respect, so this confusion is understandable.

**Comment by asikorski** [comment]
@greenrd  Thanks for information, this issues will be resolved in new release (1.4.1 //IM-433 )

**Comment by asikorski** [comment]
@greenrd Now is supported, please check https://www.npmjs.com/package/localapi
