### ISSUE TITLE
Installing local-api failed

### ISSUE THREAD

**Issue by jeppe1990** [isaacloud/local-api#47]
When I run "npm install -g localapi" in my command prompt, I get following errors:
![Console with errors](https://cloud.githubusercontent.com/assets/17174187/14108564/4eb2eb4a-f5be-11e5-903c-7ae151bb32f0.png)

I guess that some gits have been deleted/moved. 

Do you have any suggestions on fixing this?

**Comment by asikorski** [comment]
You need to install git ;)

**Comment by jeppe1990** [comment]
I had Git installed, but not enabled it from command prompt :) 
Anyway, I solved it and it wasn't an error on "your side" :)
