### ISSUE TITLE
how to listen on ip 0.0.0.0

### ISSUE THREAD

**Issue by sanlengjingvv** [isaacloud/local-api#50]
so others can access the api

**Comment by asikorski** [comment]
with version you use?

**Comment by sanlengjingvv** [comment]
v1.5.0

**Comment by wszydlak** [comment]
In version 1.5.0 You should be able to access Your API on another computer. Have You tried it? If it's not working tell me what OS are You using?

Sorry for late reply

**Comment by sanlengjingvv** [comment]
ok,I can access API from another computer.This log mislead me
> info: [localapi] App running at http://localhost:3333
