### ISSUE TITLE
Implement ability to run without generating examples from templates.

### ISSUE THREAD

**Issue by alvassin** [isaacloud/local-api#52]
Please implement ability to run without generating examples from templates (use existing).

**Comment by alvassin** [comment]
Found option according to [source code](https://github.com/isaacloud/local-api/blob/master/bin/localapi#L18) ...and later in README. Sorry. 

Perhaps it's nice idea to add all options to `localapi --help` call.

**Comment by wszydlak** [comment]
*localapi --help* contains infor about available commands and global options (such as checking version)

For each command, ex. *run* You can check extra options by running command *localapi run --help* - it will show You all the options available for *run* command
