### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by zhouhao27** [isaacloud/local-api#8]
I've copied your example to a folder and run the following command:

> localapi run raml_example_file.raml

Then it shows:

> info: [localapi] App running at http:/:::3333

Why it's not in http://localhost:3333? When I'm trying to open it in browser, the error message is:

> This resource does not exist, look into the documentation. 

What could be the reason? Thanks.

**Comment by zhouhao27** [comment]
The error message in my console:

> info: LocalAPI 1.4.0 by IsaaCloud.com
info: [localapi] Run app
info: [localapi] App running at http:/:::3333
##########################
[REST] Request
Date: Thu Oct 29 2015 15:25:34 GMT+0800 (SGT)
Method: GET
Url: /
Headers: 
 { host: 'localhost:3333',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  cookie: '__utma=111872281.677959037.1437386673.1437386673.1437386673.1; __utmz=111872281.1437386673.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _ga=GA1.1.677959037.1437386673; _ga=GA1.1.677959037.1437386673; ajs_anonymous_id=%22d8e15e4a-710c-412e-ab1f-f097e28307ce%22; ajs_group_id=null; ajs_user_id=null; ECS[visit_times]=9; hblid=YXLDvBkedPhPcrif4n6fa5Y8EHjWASFL; JSESSIONID=jl2wwj9nlmx01xd1eempsy4np; local=zhouhao; mp_64c4908de7b1aef6ecb52c1736e23c72_mixpanel=%7B%22distinct_id%22%3A%20%2214e3e35bbe05da-017acb9cd-544f7938-1fa400-14e3e35bbe17cf%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; olfsk=olfsk8884589434601367; wp-settings-time-1=1432267247',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7',
  'accept-language': 'en-us',
  'accept-encoding': 'gzip, deflate',
  connection: 'keep-alive' }
Body: 
 {}
error:  Error: Specified method not in raml
    at Object.localUtils.findMethod (/usr/local/lib/node_modules/localapi/models/apiManager.js:171:13)
    at getResponse (/usr/local/lib/node_modules/localapi/models/apiManager.js:30:30)
    at module.exports.ramlMethods (/usr/local/lib/node_modules/localapi/models/apiManager.js:250:7)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/localapi/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/localapi/node_modules/express/lib/router/route.js:131:13)
    at next (/usr/local/lib/node_modules/localapi/node_modules/express/lib/router/route.js:125:14)
    at next (/usr/local/lib/node_modules/localapi/node_modules/express/lib/router/route.js:125:14)
    at next (/usr/local/lib/node_modules/localapi/node_modules/express/lib/router/route.js:125:14)
    at next (/usr/local/lib/node_modules/localapi/node_modules/express/lib/router/route.js:125:14)
    at Route.dispatch (/usr/local/lib/node_modules/localapi/node_modules/express/lib/router/route.js:112:3)
##########################
[REST] Request

**Comment by zhouhao27** [comment]
Solve it. I'm thinking the http://localhost:3333 will show the api document like what api-designer is doing. Another question, is it possible to link api-designer to local api server? Thanks.

**Comment by dxdoan** [comment]
Looks like I'm having the same problem as described in this issue. How to solve it?

**Comment by mszopa** [comment]
Hi dxdoan,

the fake API you run with LocalAPI is available at http://localhost:3333. To make a request, you need to specify the resource which you want to operate on - which is defined in the RAML file you are running. (Note the error in the console output: 
```
error: Error: Specified method not in raml
``` 
The GET method on an empty `/` resource you are trying to use is indeed not specified in raml_example_file.raml.)
 
To retrieve a collection of users, for example, you can simply open your browser and put `http://localhost:3333/users` in the address bar.

If you want to emulate other methods described in the RAML file, you can get a REST client, such as Postman, and send PUT, POST and DELETE requests from there.

Let me know if that works for you.

Cheers!
